name: Bug Report
description: File a bug report
type: "bug"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    id: version-information
    attributes:
      label: Version information
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      multiple: true
      options:        
        - Windows
        - macOS
        - Linux
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please collect and upload Developer Tools and Diagnostics Support logs. See https://github.com/AvaloniaUI/AvaloniaUI.DeveloperTools/tree/main/docs/reporting-issue.md
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
        If applicable, add screenshots to help explain your problem.     
